api_platform:
    title: Api practice API
    version: 1.0.0
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
    docs_formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        error_formats:
            jsonproblem: ['application/json']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
