entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false

api:
    dashboard: true

tls:
    certificates:
        - certFile: /certs/agorafolk.crt
          keyFile: /certs/agorafolk.key
